
import React from 'react';

const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-20 animate-fadeIn">
      <div className="bg-gray-800/50 p-12 rounded-[48px] border border-white/5 shadow-2xl">
        <h1 className="text-4xl font-black text-white tracking-tighter mb-8">Terms of Service</h1>
        <p className="text-gray-400 mb-10 font-medium italic">Effective Date: October 2023</p>
        
        <div className="prose prose-invert max-w-none space-y-8 text-gray-300 font-medium leading-relaxed">
          <section>
            <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wider text-purple-500">1. Acceptance of Terms</h2>
            <p>
              By accessing or using VidSpark AI, you agree to be bound by these Terms of Service and all applicable laws and regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wider text-purple-500">2. Description of Service</h2>
            <p>
              VidSpark AI provides an AI-powered platform for generating video content ideas and scripts. We reserve the right to modify or discontinue the service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wider text-purple-500">3. User Conduct</h2>
            <p>
              You are responsible for all activity that occurs under your account. You agree not to use the service for any illegal or unauthorized purpose, including generating harmful or malicious content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wider text-purple-500">4. Intellectual Property</h2>
            <p>
              The content generated by the AI is intended for your use. While we do not claim ownership of your specific scripts, the underlying technology, brand, and platform architecture remain the property of VidSpark AI.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-wider text-purple-500">5. Limitation of Liability</h2>
            <p>
              VidSpark AI shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our service.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
